COTR-31-Damage-popup
Nekompiliuoja/Champions-of-the-Realm pull request #33
Opened 2023-03-26 18:54 UTC by Arnelys

Created damage indicator that pops up when player takes damage.

2023-03-26 19:37 UTC, Karolinskis commented on Scenes/UI/DamagePopup/DamagePopup.cs
> +        tween.Chain().TweenProperty(this, "scale", new Vector2(0.1f, 0.1f), 0.7f).SetDelay(0.3f);
comment these parameters for better readability

2023-03-26 19:39 UTC, Karolinskis requested changes

2023-03-26 19:39 UTC, Karolinskis commented on Scenes/UI/DamagePopup/DamagePopup.cs
> +        tween.Chain().TweenProperty(this, "scale", new Vector2(0.1f, 0.1f), 0.7f).SetDelay(0.3f);
comment these parameters for better readability

2023-03-27 11:34 UTC, Arnelys commented on Scenes/UI/DamagePopup/DamagePopup.cs
> +        tween.Chain().TweenProperty(this, "scale", new Vector2(0.1f, 0.1f), 0.7f).SetDelay(0.3f);
Done

2023-03-27 15:09 UTC, Arnelys commented on Scenes/UI/DamagePopup/DamagePopup.cs
> +    // Called when the node enters the scene tree for the first time.
Done

2023-03-27 15:10 UTC, Elijuszek approved these changes
LGTM!

2023-03-27 15:28 UTC, merged