COTR-61-loading-animation
Nekompiliuoja/Champions-of-the-Realm pull request #50
Opened 2023-04-13 17:20 UTC by disusen

Implemented a loading screen for switching between resource intensive scenes.

2023-04-14 15:05 UTC, Elijuszek requested changes
Loading screen design looks good, but it would be more appealing if Loading ProgressBar moved more dynamically instead of 0 to 100 instantly (user doesn't need to know how accurate it is). Also it would be a great idea to change background to something more colorful

2023-04-15 10:49 UTC, Elijuszek requested changes

2023-04-15 10:49 UTC, Elijuszek commented on Scenes/UI/Menus/Main/MainMenu.tscn
MainMenu background is missing, probably removed by accident

2023-04-15 10:49 UTC, Elijuszek commented on Scenes/Globals/Globals.cs
> +        LoadingScreen loadingScreen = loadingScreenScene.Instantiate() as LoadingScreen;
Rewrite this line like this:
LoadingScreen loadingScreen = loadingScreenScene.Instantiate<LoadingScreen>();

2023-04-15 10:49 UTC, Elijuszek commented on Scenes/UI/Menus/GameOver/GameOver.cs
Use 4 spaces for indentation instead of tabs

2023-04-15 12:00 UTC, Elijuszek requested changes
- Unresolved issues in LoadingScreen.cs (4 spaces instead of tabs, add summary for loadingBarStatus")
- Changes in Globals.cs are needed

2023-04-15 13:11 UTC, Karolinskis requested changes

2023-04-15 13:11 UTC, Karolinskis commented on Scenes/UI/Menus/GameOver/GameOver.cs
> +        GetTree().Paused = false;
Inconsistent spacing, this might be due to different spacing. Use 4 spaces in your IDE

2023-04-15 13:11 UTC, Karolinskis commented on Scenes/UI/Menus/Loading/LoadingScreen.cs
> +	private AnimationPlayer animationPlayer;	// animation player node
Inconsistent spacing, see previous comment for more info

2023-04-15 13:11 UTC, Karolinskis commented on Scenes/UI/Menus/Loading/LoadingScreen.cs
> +	/// <param name="value">Loading bar progress.</param>
There is no parameter named value in this method

2023-04-15 13:11 UTC, Karolinskis commented on COTR.csproj.old
Unneeded file, please remove.

2023-04-15 13:18 UTC, Karolinskis commented
Don't use commit messages as just `COTR-61-Loading-animation`. 

- The stiling should be `COTR-[NUM] commit message`. 
- Don't use more dashes than needed. 
- Don't spam every commit with just `Loading animation` these descriptions should be a short summary of what you edited, for example `COTR-61 Fixed styles in x method`. Your current commit messages are not informative to the user checking through the the code to understand why some changes were made.

2023-04-15 13:43 UTC, Elijuszek requested changes

2023-04-15 13:43 UTC, Elijuszek commented on Scenes/UI/Menus/Loading/LoadingScreen.cs
> +			if (sceneLoadStatus == ResourceLoader.ThreadLoadStatus.Loaded)
Infinite loop possibility, it may cause debugging problems in the future. Replace if statement with switch statement for every `ResourceLoader.ThreadLoadStatus`, you should use `GD.PrintErr("Error message");` to notify about unwanted state (For example: `InvalidResource`, `Failed`) also modify while loop to something like this:
`while(sceneLoadStatus == ResourceLoader.ThreadLoadStatus.InProgress)`

2023-04-15 14:27 UTC, Karolinskis requested changes
Change all commit messages, to more clearly represent the committed changes.
See [here](https://docs.github.com/en/pull-requests/committing-changes-to-your-project/creating-and-editing-commits/changing-a-commit-message) for more information.

2023-04-15 15:26 UTC, Elijuszek requested changes

2023-04-15 15:26 UTC, Elijuszek commented on Scenes/UI/Menus/Loading/LoadingScreen.cs
> +                    break;
- Add GD.PrintErr("State doesn't exist");
- Return instead of breaking

2023-04-15 15:58 UTC, Karolinskis commented
You still haven't removed the wrong commits, you have two options:
- Remove the new commits that you piled on top and rename the original ones
- Remove all commits with the wrong commit names.

Before doing any of this I strongly recommend you create a backup branch of this branch before making any of these changes.

2023-04-15 16:00 UTC, Elijuszek requested changes

2023-04-15 16:00 UTC, Elijuszek commented on Scenes/UI/Menus/Loading/LoadingScreen.cs
Fix indentation, use 4 spaces instead of tabs. There are still tabs in "InitializeResourceLoader" method.

2023-04-15 16:00 UTC, Elijuszek commented on Scenes/UI/Menus/Loading/LoadingScreen.cs
> +        ResourceLoader.LoadThreadedRequest(nextScene);  // Begin loading
Rewrite like this:
`ResourceLoader.LoadThreadedRequest(nextScene);`
`ResourceLoader.ThreadLoadStatus sceneLoadStatus = ResourceLoader.LoadThreadedGetStatus(nextScene);`

2023-04-15 17:15 UTC, closed without merging