COTR-65 further GUI improvements
Nekompiliuoja/Champions-of-the-Realm pull request #54
Opened 2023-04-15 21:53 UTC by Arnelys

Added better health bar styling.

Added golden coin popup animation when change currency method is called.

2023-04-15 22:23 UTC, Elijuszek requested changes

2023-04-15 22:23 UTC, Elijuszek commented on Scenes/UI/HUD/GUI.cs
> +
Add comment "Tweening gold text"

2023-04-15 22:23 UTC, Elijuszek commented on Scenes/UI/HUD/GUI.cs
> +
Add comment "Tweening golden coin"

2023-04-15 22:23 UTC, Elijuszek commented on Scenes/UI/HUD/HUD.tscn
> +[ext_resource type="Texture2D" uid="uid://bkdy38u5jlvjk" path="res://Sprites/UI/Currency/GoldenCoin.png" id="2_fw1db"]
`GoldenCoin.png` should be moved to `res://Sprites/Loot/Coins/GoldenCoin.png`

2023-04-15 22:23 UTC, Elijuszek commented on Scenes/UI/HUD/GUI.cs
> +    private Vector2 baseGoldCoinCoordinates;
Comment why do you need this variable

2023-04-15 23:30 UTC, Arnelys commented on Scenes/UI/HUD/GUI.cs
> +
Done

2023-04-15 23:30 UTC, Arnelys commented on Scenes/UI/HUD/GUI.cs
> +
Done

2023-04-15 23:33 UTC, Arnelys commented on Scenes/UI/HUD/HUD.tscn
> +[ext_resource type="Texture2D" uid="uid://bkdy38u5jlvjk" path="res://Sprites/UI/Currency/GoldenCoin.png" id="2_fw1db"]
Done

2023-04-15 23:33 UTC, Arnelys commented on Scenes/UI/HUD/GUI.cs
> +    private Vector2 baseGoldCoinCoordinates;
Done

2023-04-16 08:03 UTC, Elijuszek submitted a review, later dismissed
Unresolved conflicts

2023-04-16 20:28 UTC, Karolinskis approved these changes
LGTM

2023-04-16 20:29 UTC, merged