COTR-83 Enemies can get stuck behind obstacles
Nekompiliuoja/Champions-of-the-Realm pull request #74
Opened 2023-04-29 22:34 UTC by Karolinskis

Implemented a fix for this using Navigation layers.

Due to this feature being quite new in Godot there are a few limitations:
- **The NavigationAgent2D node doesn't read Physics layers**
  To fix this issue, I had to use two different tiles. All tiles that do not have any obstacles have a navigation mesh and the one's that do use a different ground tile, that doesn't have a navigation mesh. 
- **NavigationAgent2D path-finding tends to get stuck on corners**
  To fix this issue, I had to make the navigation meshes smaller than the actual tile and edit the project settings to make the default navigation edge connection margin bigger. __This tends to make load times longer and editing the tile-map takes more time__.

2023-04-29 22:36 UTC, Karolinskis commented on Sprites/Maps/Environment/Tilesets/LiquidMerged.png
Two identical tile-maps had to be merged due to the fact that the current tile map doesn't contain middle liquid tiles.

2023-04-29 22:37 UTC, Karolinskis commented on Sprites/Maps/Environment/Tilesets/LiquidMerged.png
Two identical tile-maps had to be merged due to the fact that the current tile map doesn't contain middle liquid tiles.

2023-04-29 22:38 UTC, Karolinskis commented on Scenes/Actors/Troops/MeleeAI.cs
>                  Rotation = GlobalPosition.DirectionTo(target.GlobalPosition).Angle();
This should be changed because while the enemy is moving the sprite tends to jitter.

2023-04-30 09:13 UTC, Elijuszek requested changes

2023-04-30 09:13 UTC, Elijuszek commented on Scenes/Actors/Troops/MeleeAI.cs
> +        navAgent.AvoidanceEnabled = true;
You can set `AvoidanceEnabled` in the editor
![image](https://user-images.githubusercontent.com/56361945/235344775-20ac8869-875c-4a54-b1ed-aa1a1061e9f7.png)

2023-04-30 09:13 UTC, Elijuszek commented on Scenes/Actors/Troops/Infantry/FootmanEnemy.tscn
It might be more convenient to move NavigationAgent2D node to Infantry object, by doing so all the derived infantry troops would inherit this specific node.

2023-04-30 09:13 UTC, Elijuszek commented on Scenes/Actors/Troops/MeleeAI.cs
> +    private NavigationAgent2D navAgent;
Comment this variable

2023-04-30 09:13 UTC, Elijuszek commented on Scenes/Actors/Troops/MeleeAI.cs
> +        navAgent.TargetPosition = target.GlobalPosition;
Might cause error if target instance is not valid

2023-04-30 14:09 UTC, Karolinskis commented
[This](https://github.com/Nekompiliuoja/Champions-of-the-Realm/pull/74/files#diff-0c1fec70c46f24406929ba66b7b29d76b244204044a07cdbdf2909c18854a349R21) might come in handy if we ever decide to add a debug menu.

2023-04-30 19:11 UTC, Elijuszek requested changes

2023-04-30 19:11 UTC, Elijuszek commented on Scenes/Actors/Troops/MeleeAI.cs
> +    private bool DEBUG = false; // Enables debugging options
Add Export attribute for this variable so it could be changed inside editor when debugging

2023-04-30 21:17 UTC, Elijuszek approved these changes
LGTM!

2023-04-30 21:17 UTC, merged