COTR-105 Implemented shop functionality
Nekompiliuoja/Champions-of-the-Realm pull request #91
Opened 2023-05-14 18:22 UTC by disusen

Implemented basic shop functionality which allows the user to spend his coins on various weapons found in the shop.

2023-05-14 19:07 UTC, Elijuszek requested changes
- Error when switching weapons
- Files which haven't been touched shouldn't be committed (`.tscn` files)
- When work is of large scope and working across multiple classes changes should be staged into multiple commits (for example two commits for: changes in `Shop.cs` and changes in `WeaponsManager.cs`)

2023-05-14 21:12 UTC, Karolinskis requested changes

2023-05-14 21:12 UTC, Karolinskis commented on Scenes/Actors/Player/WeaponsManager.cs
> +    public bool AddWeapon(Weapon weapon, int index)
Due to changing return from `void` to `bool` the summary above this method is incorrect add `<returns>`

2023-05-14 21:12 UTC, Karolinskis commented on Scenes/Actors/Player/WeaponsManager.cs
> +    public void ChangeWeapon(int indexToChangeTo)
Incorrect summary add <param name="indexToChangeTo">

2023-05-14 21:12 UTC, Karolinskis commented on Scenes/UI/HUD/GUI.cs
> +    }
This code is unmaintainable. This should probably be one method called `ItemPressed` that you pass and argument in which you tell which button was pressed.

2023-05-15 17:02 UTC, Elijuszek requested changes

2023-05-15 19:09 UTC, Karolinskis requested changes
If nothing was bought from the store, the player should spawn with no weapon. And the inventory should be empty.

2023-05-15 19:46 UTC, Karolinskis requested changes
Bug mentioned in https://github.com/Nekompiliuoja/Champions-of-the-Realm/pull/91/commits/f417eedfae778c73d4378ad736635058b80565ac still persists

2023-05-15 20:00 UTC, Karolinskis requested changes

2023-05-15 20:12 UTC, Karolinskis requested changes
When starting a new game in the debuger an error pops up

2023-05-15 20:12 UTC, Karolinskis commented
> When starting a new game in the debuger an error pops up

---
E 0:00:08:0416   Godot.NativeInterop.NativeFuncs.generated.cs:1535 @ void Godot.NativeInterop.NativeFuncs.godotsharp_pusherror(Godot.NativeInterop.godot_string& ): Calling Idle method from weapon class
  <C++ Source>   modules/mono/glue/runtime_interop.cpp:1303 @ godotsharp_pusherror()
  <Stack Trace>  Godot.NativeInterop.NativeFuncs.generated.cs:1535 @ void Godot.NativeInterop.NativeFuncs.godotsharp_pusherror(Godot.NativeInterop.godot_string& )
                 GD.cs:351 @ void Godot.GD.PushError(System.String )
                 Weapon.cs:42 @ void ChampionsOfTheRealm.Weapon.Idle()
                 Melee.cs:22 @ void ChampionsOfTheRealm.Melee._Ready()
                 Node.cs:1801 @ Boolean Godot.Node.InvokeGodotClassMethod(Godot.NativeInterop.godot_string_name& , Godot.NativeInterop.NativeVariantPtrArgs , Godot.NativeInterop.godot_variant& )
                 CanvasItem.cs:1371 @ Boolean Godot.CanvasItem.InvokeGodotClassMethod(Godot.NativeInterop.godot_string_name& , Godot.NativeInterop.NativeVariantPtrArgs , Godot.NativeInterop.godot_variant& )
                 Node2D.cs:516 @ Boolean Godot.Node2D.InvokeGodotClassMethod(Godot.NativeInterop.godot_string_name& , Godot.NativeInterop.NativeVariantPtrArgs , Godot.NativeInterop.godot_variant& )
                 ChampionsOfTheRealm.Weapon_ScriptMethods.generated.cs:61 @ Boolean ChampionsOfTheRealm.Weapon.InvokeGodotClassMethod(Godot.NativeInterop.godot_string_name& , Godot.NativeInterop.NativeVariantPtrArgs , Godot.NativeInterop.godot_variant& )
                 ChampionsOfTheRealm.Melee_ScriptMethods.generated.cs:75 @ Boolean ChampionsOfTheRealm.Melee.InvokeGodotClassMethod(Godot.NativeInterop.godot_string_name& , Godot.NativeInterop.NativeVariantPtrArgs , Godot.NativeInterop.godot_variant& )
                 CSharpInstanceBridge.cs:24 @ Godot.NativeInterop.godot_bool Godot.Bridge.CSharpInstanceBridge.Call(IntPtr , Godot.NativeInterop.godot_string_name* , Godot.NativeInterop.godot_variant** , Int32 , Godot.NativeInterop.godot_variant_call_error* , Godot.NativeInterop.godot_variant* )
                 Godot.NativeInterop.NativeFuncs.generated.cs:332 @ void Godot.NativeInterop.NativeFuncs.godotsharp_method_bind_ptrcall(IntPtr , IntPtr , System.Void** , System.Void* )
                 NativeCalls.cs:5859 @ void Godot.NativeCalls.godot_icall_3_655(IntPtr , IntPtr , IntPtr , Godot.NativeInterop.godot_bool , Int32 )
                 Node.cs:600 @ void Godot.Node.AddChild(Godot.Node , Boolean , Godot.Node+InternalMode )
                 Map.cs:127 @ void ChampionsOfTheRealm.Map.SpawnPlayer()
                 Map.cs:53 @ void ChampionsOfTheRealm.Map._Ready()
                 Node.cs:1801 @ Boolean Godot.Node.InvokeGodotClassMethod(Godot.NativeInterop.godot_string_name& , Godot.NativeInterop.NativeVariantPtrArgs , Godot.NativeInterop.godot_variant& )
                 CanvasItem.cs:1371 @ Boolean Godot.CanvasItem.InvokeGodotClassMethod(Godot.NativeInterop.godot_string_name& , Godot.NativeInterop.NativeVariantPtrArgs , Godot.NativeInterop.godot_variant& )
                 Node2D.cs:516 @ Boolean Godot.Node2D.InvokeGodotClassMethod(Godot.NativeInterop.godot_string_name& , Godot.NativeInterop.NativeVariantPtrArgs , Godot.NativeInterop.godot_variant& )
                 ChampionsOfTheRealm.Map_ScriptMethods.generated.cs:96 @ Boolean ChampionsOfTheRealm.Map.InvokeGodotClassMethod(Godot.NativeInterop.godot_string_name& , Godot.NativeInterop.NativeVariantPtrArgs , Godot.NativeInterop.godot_variant& )
                 CSharpInstanceBridge.cs:24 @ Godot.NativeInterop.godot_bool Godot.Bridge.CSharpInstanceBridge.Call(IntPtr , Godot.NativeInterop.godot_string_name* , Godot.NativeInterop.godot_variant** , Int32 , Godot.NativeInterop.godot_variant_call_error* , Godot.NativeInterop.godot_variant* )
                 Godot.NativeInterop.NativeFuncs.generated.cs:332 @ void Godot.NativeInterop.NativeFuncs.godotsharp_method_bind_ptrcall(IntPtr , IntPtr , System.Void** , System.Void* )
                 NativeCalls.cs:5859 @ void Godot.NativeCalls.godot_icall_3_655(IntPtr , IntPtr , IntPtr , Godot.NativeInterop.godot_bool , Int32 )
                 Node.cs:600 @ void Godot.Node.AddChild(Godot.Node , Boolean , Godot.Node+InternalMode )
                 LoadingScreen.cs:96 @ void ChampionsOfTheRealm.LoadingScreen.AddScene()
                 LoadingScreen.cs:71 @ void ChampionsOfTheRealm.LoadingScreen.InitializeResourceLoader()
                 ChampionsOfTheRealm.LoadingScreen_ScriptMethods.generated.cs:54 @ Boolean ChampionsOfTheRealm.LoadingScreen.InvokeGodotClassMethod(Godot.NativeInterop.godot_string_name& , Godot.NativeInterop.NativeVariantPtrArgs , Godot.NativeInterop.godot_variant& )
                 CSharpInstanceBridge.cs:24 @ Godot.NativeInterop.godot_bool Godot.Bridge.CSharpInstanceBridge.Call(IntPtr , Godot.NativeInterop.godot_string_name* , Godot.NativeInterop.godot_variant** , Int32 , Godot.NativeInterop.godot_variant_call_error* , Godot.NativeInterop.godot_variant* )

2023-05-15 20:36 UTC, Karolinskis approved these changes

2023-05-15 20:39 UTC, Karolinskis requested changes

2023-05-15 20:39 UTC, Karolinskis commented on Scenes/UI/HUD/GUI.cs
> +            itemArray[i].Pressed += () => SwitchItem(currentIndex);
Refactor this

2023-05-15 20:50 UTC, Karolinskis requested changes

2023-05-15 20:50 UTC, Karolinskis commented on Scenes/UI/HUD/GUI.cs
> +            button.Pressed += () => SwitchItem(ButtonIndex);
This anonymous lambda expression effects code readability in a bad way, please Refactor this part.

2023-05-15 21:29 UTC, Karolinskis requested changes

2023-05-15 21:29 UTC, Karolinskis commented on Scenes/UI/HUD/GUI.cs
> +        }
Refactor this whole part, don't assign methods through code you can do this through the editor.
![image](https://github.com/Nekompiliuoja/Champions-of-the-Realm/assets/68164180/4d321606-489e-4fe7-a96d-735aebc2e8a9)

2023-05-15 21:49 UTC, Karolinskis requested changes

2023-05-15 21:49 UTC, Karolinskis commented on Scenes/UI/HUD/GUI.cs
> +    [Signal] public delegate void WeaponSwitchedEventHandler(int index);
Why did you add this delegate? It's not needed

2023-05-15 21:54 UTC, Karolinskis requested changes

2023-05-15 21:54 UTC, Karolinskis commented on Scenes/Actors/Player/WeaponsManager.cs
> +            Array.Resize(ref weapons, index + 1);
What's the point of resizing the array when the array is constantly size of 3?

2023-05-15 21:59 UTC, Elijuszek requested changes

2023-05-15 21:59 UTC, Elijuszek commented on Scenes/UI/HUD/GUI.cs
> +        itemArray[index].FocusMode = Godot.Control.FocusModeEnum.All;
Remove this unnecessary line. By default buttons `focusMode = All`.

2023-05-15 22:03 UTC, Elijuszek commented on Scenes/UI/HUD/GUI.cs
> +        itemArray[index].FocusMode = Godot.Control.FocusModeEnum.All;
Okay makes sense

2023-05-15 22:07 UTC, disusen commented on Scenes/Actors/Player/WeaponsManager.cs
> +            Array.Resize(ref weapons, index + 1);
The array has a maximum of size 3 for items attached through the editor, if any items are added dynamically, like in the shop then array will have to be resized.

2023-05-15 22:10 UTC, Karolinskis approved these changes

2023-05-15 22:11 UTC, Elijuszek approved these changes
LFTM!

2023-05-15 22:12 UTC, merged